database:
  host: "127.0.0.1"
  port: 5432
  db_name: "postgres"  # updated from "Local Postgres" to valid identifier
  schema_paper: "public"
  schema_live: "live"
  username: "postgres"
  password: "Goodmorning@123"
